# Generated by Django 5.2.10 on 2026-01-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a happy tourist image', upload_to='gallery/')),
                ('caption', models.CharField(help_text='E.g., Travel Place Name', max_length=200)),
                ('tourist_name', models.CharField(blank=True, help_text='Optional: Name of the tourist', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
