# Generated by Django 5.2.4 on 2026-01-06 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main banner heading', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle/description (optional)', max_length=200)),
                ('image', models.ImageField(help_text='Banner image (1920x600px recommended)', upload_to='banners/')),
                ('button_text', models.CharField(blank=True, help_text='Call-to-action button text', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='Button link URL', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (1, 2, 3...)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide?')),
            ],
            options={
                'verbose_name': 'Banner Slide',
                'verbose_name_plural': 'Banner Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='College name', max_length=200)),
                ('tagline', models.CharField(help_text='College tagline/motto', max_length=200)),
                ('about', models.TextField(help_text='About the college')),
                ('vision', models.TextField(help_text='College vision statement')),
                ('mission', models.TextField(help_text='College mission statement')),
                ('principal_name', models.CharField(help_text="Principal's name", max_length=100)),
                ('principal_message', models.TextField(help_text='Message from the principal')),
                ('principal_photo', models.ImageField(blank=True, help_text="Principal's photo", upload_to='college/')),
                ('address', models.TextField(help_text='Complete college address')),
                ('phone', models.CharField(help_text='Contact phone number(s)', max_length=50)),
                ('email', models.EmailField(help_text='Official email address', max_length=254)),
                ('website', models.URLField(blank=True, help_text='College website URL')),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn page URL')),
                ('google_maps_embed', models.TextField(blank=True, help_text='Paste Google Maps iframe embed code here')),
            ],
            options={
                'verbose_name': 'College Information',
                'verbose_name_plural': 'College Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's name", max_length=100)),
                ('email', models.EmailField(help_text="Sender's email", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="Sender's phone (optional)", max_length=15)),
                ('subject', models.CharField(help_text='Message subject', max_length=200)),
                ('message', models.TextField(help_text='Message content')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Has admin read this message?')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (e.g., Computer Science)', max_length=100)),
                ('code', models.CharField(help_text='Department code (e.g., CS, MBA)', max_length=10, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the department')),
                ('image', models.ImageField(blank=True, help_text='Department image', null=True, upload_to='courses/')),
                ('hod_name', models.CharField(help_text='Name of HOD', max_length=100, verbose_name='Head of Department')),
                ('duration', models.CharField(help_text='Course duration (e.g., 3 Years, 4 Years)', max_length=50)),
                ('eligibility', models.TextField(help_text='Eligibility criteria for admission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this department active?')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title', max_length=100)),
                ('category', models.CharField(choices=[('campus', 'Campus'), ('labs', 'Laboratories'), ('classrooms', 'Classrooms'), ('events', 'Events'), ('sports', 'Sports'), ('library', 'Library')], help_text='Image category', max_length=20)),
                ('image', models.ImageField(help_text='Upload image file', upload_to='gallery/')),
                ('description', models.TextField(blank=True, help_text='Optional image description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notice title/heading', max_length=200)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('examination', 'Examination'), ('admission', 'Admission'), ('event', 'Event'), ('general', 'General')], default='general', max_length=20)),
                ('content', models.TextField(help_text='Full notice content')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When to publish this notice')),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important (shows with red badge)')),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='notices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Student's full name", max_length=100)),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=15)),
                ('qualification', models.CharField(help_text='Current educational qualification', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Additional message/questions')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False, help_text='Has been contacted by admin?')),
                ('course_interested', models.ForeignKey(help_text='Course/Department interested in', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.department')),
            ],
            options={
                'verbose_name': 'Admission Inquiry',
                'verbose_name_plural': 'Admission Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of faculty member', max_length=100)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('associate', 'Associate Professor'), ('assistant', 'Assistant Professor'), ('lecturer', 'Lecturer')], help_text='Job designation', max_length=20)),
                ('qualification', models.CharField(help_text='Highest qualification (e.g., Ph.D., M.Tech)', max_length=200)),
                ('experience', models.CharField(help_text='Years of experience (e.g., 10 Years)', max_length=50)),
                ('email', models.EmailField(help_text='Official email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact number', max_length=15)),
                ('photo', models.ImageField(blank=True, help_text='Faculty photo', null=True, upload_to='faculty/')),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower number = higher priority)')),
                ('department', models.ForeignKey(help_text='Department this faculty belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='main.department')),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty',
                'ordering': ['order', 'name'],
            },
        ),
    ]
